#!/usr/bin/env perl
# -*- cperl -*-
use strict;
use POSIX();

sub str2name
{
  my ($str) = @_;
  $str = lc($str);

  my $result = "unknown";

  my @nics_system_names = (
                           "kraken",
                           "darter",
                           "kids",
                           "keenland",
                           "titan",
                           );

  for my $name(@nics_system_names)
    {
      if ($str =~ m/$name/)
        {
          $result = $name;
        }
    }
  return $result
}

sub main
{
  my $host = `hostname -f`;
  chomp($host);

  my $result = str2name($host);

  if ($result eq "unknown")
    {
      my ($sysname, $nodename, $release, $version, $machine) = POSIX::uname();
      $result = str2name($nodename);
    }
  print "$result\n";
}

main();
