#!/usr/bin/env perl
# -*- cperl -*-
#
# Git Version: @git@

#-----------------------------------------------------------------------
# XALT: A tool that tracks users jobs and environments on a cluster.
# Copyright (C) 2013-2014 University of Texas at Austin
# Copyright (C) 2013-2014 University of Tennessee
#
# This library is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation; either version 2.1 of
# the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser  General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free
# Software Foundation, Inc., 59 Temple Place, Suite 330,
# Boston, MA 02111-1307 USA
#-----------------------------------------------------------------------
use strict;
use POSIX();

sub str2name
{
  my ($str) = @_;
  $str = lc($str);

  my $result = "unknown";

  my %nics_system_names = (
                           "kraken"   => "kraken",
                           "darter"   => "darter",
                           "kid"      => "kids",
                           "keenland" => "keenland",
                           "titan"    => "titan",
                           );

  for my $name(keys(%nics_system_names))
    {
      if ($str =~ m/$name/)
        {
          $result = $nics_system_names{$name};
        }
    }
  return $result
}

sub main
{
  my $host = `hostname -f`;
  chomp($host);

  my $result = str2name($host);

  if ($result eq "unknown")
    {
      my ($sysname, $nodename, $release, $version, $machine) = POSIX::uname();
      $result = str2name($nodename);
    }
  print "$result\n";
}

main();
